// src/components/CTAComponent.vue
<template>
  <div class="relative isolate mt-32 px-6 py-32 sm:mt-56 sm:py-40 lg:px-8">
    <svg
      class="absolute inset-0 -z-10 h-full w-full stroke-white/10 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]"
      aria-hidden="true"
    >
      <defs>
        <pattern
          id="1d4240dd-898f-445f-932d-e2872fd12de3"
          width="200"
          height="200"
          x="50%"
          y="0"
          patternUnits="userSpaceOnUse"
        >
          <path d="M.5 200V.5H200" fill="none" />
        </pattern>
      </defs>
      <svg x="50%" y="0" class="overflow-visible fill-gray-800/20">
        <path
          d="M-200 0h201v201h-201Z M600 0h201v201h-201Z M-400 600h201v201h-201Z M200 800h201v201h-201Z"
          stroke-width="0"
        />
      </svg>
      <rect
        width="100%"
        height="100%"
        stroke-width="0"
        fill="url(#1d4240dd-898f-445f-932d-e2872fd12de3)"
      />
    </svg>
    <div
      class="absolute inset-x-0 top-10 -z-10 flex transform-gpu justify-center overflow-hidden blur-3xl"
      aria-hidden="true"
    >
      <div
        class="aspect-[1108/632] w-[69.25rem] flex-none bg-gradient-to-r from-[#80caff] to-[#4f46e5] opacity-20"
        style="
          clip-path: polygon(
            73.6% 51.7%,
            91.7% 11.8%,
            100% 46.4%,
            97.4% 82.2%,
            92.5% 84.9%,
            75.7% 64%,
            55.3% 47.5%,
            46.5% 49.4%,
            45% 62.9%,
            50.3% 87.2%,
            21.3% 64.1%,
            0.1% 100%,
            5.4% 51.1%,
            21.4% 63.9%,
            58.9% 0.2%,
            73.6% 51.7%
          );
        "
      />
    </div>
    <div class="mx-auto max-w-2xl text-center">
      <h2 class="text-3xl font-bold tracking-tight text-white sm:text-4xl">
        Give your Laravel app the eloquent writing experience it deserves.
      </h2>
      <p class="mx-auto mt-6 max-w-xl text-lg leading-8 text-gray-300">
        Not convinced yet? Try the links below to read more about what Canvas
        can do for you or spin up a live demo of your own with
        <a href="https://www.gitpod.io" class="font-bold" target="_blank"
          >Gitpod</a
        >.
      </p>
      <div class="mt-10 flex items-center justify-center gap-x-6">
        <a
          href="https://github.com/austintoddj/canvas#introduction"
          class="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
          >Get started</a
        >
        <a
          href="https://gitpod.io/#https://github.com/austintoddj/canvas/tree/master"
          class="text-sm font-semibold leading-6 text-white"
          >Live demo <span aria-hidden="true">→</span></a
        >
      </div>
    </div>
  </div>
</template>

// components/cta.tsx
import { ArrowRightIcon, GitHubIcon } from './icons';







export function Cta() {
  return (
    <section className="border-t border-canvas-100 py-24 sm:py-32 dark:border-canvas-900">
      <div className="mx-auto max-w-5xl px-6">
        <div className="relative overflow-hidden rounded-3xl bg-canvas-900 px-8 py-16 text-center sm:px-16 sm:py-20 dark:bg-white">
          <div className="bg-grid absolute inset-0 opacity-20 dark:opacity-10" />
          <div className="relative">
            <h2 className="mb-4 text-2xl font-semibold tracking-tight text-white sm:text-3xl dark:text-canvas-900">
              Give your Laravel app the eloquent writing<br />experience it deserves
            </h2>
            <p className="mx-auto mb-8 max-w-md text-[15px] text-canvas-300 dark:text-canvas-600">
              Not convinced yet? Try the links below to read more about what
              Canvas can do for you or spin up a live demo of your own with
              Gitpod.
            </p>
            <div className="flex flex-col items-center justify-center gap-3 sm:flex-row">
              <a
                href="#install"
                className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-2.5 text-sm font-medium text-canvas-900 transition-all hover:bg-canvas-100 dark:bg-canvas-900 dark:text-white dark:hover:bg-canvas-800"
              >
                Install Canvas
                <ArrowRightIcon className="h-4 w-4" />
              </a>
              <a
                href="https://github.com/austintoddj/canvas"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-full border border-canvas-700 px-5 py-2.5 text-sm font-medium text-white transition-all hover:bg-white/10 dark:border-canvas-300 dark:text-canvas-900 dark:hover:bg-canvas-900/10"
              >
                <GitHubIcon className="h-4 w-4" />
                Star on GitHub
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
