// src/components/HeroComponent.vue
<template>
    <div class="relative isolate overflow-hidden bg-gray-900">
        <svg
            class="absolute inset-0 -z-10 h-full w-full stroke-white/10 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]"
            aria-hidden="true"
        >
            <defs>
                <pattern
                    id="983e3e4c-de6d-4c3f-8d64-b9761d1534cc"
                    width="200"
                    height="200"
                    x="50%"
                    y="-1"
                    patternUnits="userSpaceOnUse"
                >
                    <path d="M.5 200V.5H200" fill="none" />
                </pattern>
            </defs>
            <svg x="50%" y="-1" class="overflow-visible fill-gray-800/20">
                <path
                    d="M-200 0h201v201h-201Z M600 0h201v201h-201Z M-400 600h201v201h-201Z M200 800h201v201h-201Z"
                    stroke-width="0"
                />
            </svg>
            <rect
                width="100%"
                height="100%"
                stroke-width="0"
                fill="url(#983e3e4c-de6d-4c3f-8d64-b9761d1534cc)"
            />
        </svg>
        <div
            class="absolute left-[calc(50%-4rem)] top-10 -z-10 transform-gpu blur-3xl sm:left-[calc(50%-18rem)] lg:left-48 lg:top-[calc(50%-30rem)] xl:left-[calc(50%-24rem)]"
            aria-hidden="true"
        >
            <div
                class="aspect-[1108/632] w-[69.25rem] bg-gradient-to-r from-[#80caff] to-[#4f46e5] opacity-20"
                style="
                    clip-path: polygon(
                        73.6% 51.7%,
                        91.7% 11.8%,
                        100% 46.4%,
                        97.4% 82.2%,
                        92.5% 84.9%,
                        75.7% 64%,
                        55.3% 47.5%,
                        46.5% 49.4%,
                        45% 62.9%,
                        50.3% 87.2%,
                        21.3% 64.1%,
                        0.1% 100%,
                        5.4% 51.1%,
                        21.4% 63.9%,
                        58.9% 0.2%,
                        73.6% 51.7%
                    );
                "
            />
        </div>
        <div
            class="mx-auto max-w-7xl px-6 pb-24 pt-10 sm:pb-40 lg:flex lg:px-8 lg:pt-40"
        >
            <div
                class="mx-auto max-w-2xl flex-shrink-0 lg:mx-0 lg:max-w-xl lg:pt-8"
            >
                <img
                    class="h-11"
                    src="https://tailwindui.com/img/logos/mark.svg?color=indigo&amp;shade=500"
                    alt="Your Company"
                />
                <div class="mt-24 sm:mt-32 lg:mt-16">
                    <a
                        v-if="release"
                        :href="release.html_url"
                        class="inline-flex space-x-6"
                        target="_blank"
                    >
                        <span
                            class="rounded-full bg-indigo-500/10 px-3 py-1 text-sm font-semibold leading-6 text-indigo-400 ring-1 ring-inset ring-indigo-500/20"
                            >What's new</span
                        >
                        <span
                            class="inline-flex items-center space-x-2 text-sm font-medium leading-6 text-gray-300"
                        >
                            <span>Just shipped {{ release.tag_name }}</span>
                            <ChevronRightIcon
                                class="h-5 w-5 text-gray-500"
                                aria-hidden="true"
                            />
                        </span>
                    </a>
                </div>
                <h1
                    class="mt-10 text-4xl font-bold tracking-tight text-white sm:text-6xl"
                >
                    Publishing on your own terms
                </h1>
                <p class="mt-6 text-lg leading-8 text-gray-300">
                    Canvas is a powerful tool for Laravel apps that makes it
                    easy to write, edit, and brand your work with a range of
                    publishing tools.
                </p>
                <div class="mt-10 flex items-center gap-x-6">
                    <a
                        href="https://github.com/austintoddj/canvas#introduction"
                        class="rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-400"
                        target="_blank"
                        >Get started</a
                    >
                    <a
                        href="https://gitpod.io/#https://github.com/austintoddj/canvas/tree/master"
                        class="text-sm font-semibold leading-6 text-white"
                        target="_blank"
                        >Live demo <span aria-hidden="true">→</span></a
                    >
                </div>
            </div>
            <div
                class="mx-auto mt-16 flex max-w-2xl sm:mt-24 lg:ml-10 lg:mr-0 lg:mt-0 lg:max-w-none lg:flex-none xl:ml-32"
            >
                <div class="max-w-3xl flex-none sm:max-w-5xl lg:max-w-none">
                    <img
                        src="https://tailwindui.com/img/component-images/dark-project-app-screenshot.png"
                        alt="App screenshot"
                        width="2432"
                        height="1442"
                        class="w-[76rem] rounded-md bg-white/5 shadow-2xl ring-1 ring-white/10"
                    />
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref, watchEffect } from 'vue'
import { ChevronRightIcon } from '@heroicons/vue/20/solid'

const repo = ref(null)
const release = ref(null)

watchEffect(async () => {
    repo.value = await (
        await fetch('https://api.github.com/repos/austintoddj/canvas')
    ).json()

    release.value = await (
        await fetch(
            'https://api.github.com/repos/austintoddj/canvas/releases/latest'
        )
    ).json()
})
</script>

// components/hero.tsx
import {
  ArrowRightIcon,
  GitHubIcon,
  LaravelIcon,
  PhpIcon,
  ReactIcon,
  TailwindIcon
} from './icons'

type HeroProps = {
  latestVersion?: string | null
  latestReleaseUrl?: string | null
}

export function Hero({ latestVersion, latestReleaseUrl }: HeroProps) {
  const shippedLabel = latestVersion
    ? `Just shipped ${latestVersion}`
    : 'Just shipped'
  const releaseHref =
    latestReleaseUrl ?? 'https://github.com/austintoddj/canvas/releases/latest'

  return (
    <section className="relative overflow-hidden pt-32 pb-16 sm:pt-40 sm:pb-24">
      <div className="bg-grid absolute inset-0 opacity-60" />
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-white dark:to-canvas-950" />

      <div className="relative mx-auto max-w-5xl px-6 text-center">
        <a
          href={releaseHref}
          target="_blank"
          rel="noopener noreferrer"
          className="mb-8 inline-flex animate-fade-in items-center gap-2 rounded-full border border-canvas-200 bg-white/60 px-3 py-1 text-[12px] font-medium text-canvas-600 backdrop-blur transition-colors hover:border-canvas-300 hover:text-canvas-900 dark:border-canvas-800 dark:bg-canvas-900/60 dark:text-canvas-400 dark:hover:border-canvas-700 dark:hover:text-white"
        >
          <span className="relative flex h-1.5 w-1.5">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
            <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-emerald-500" />
          </span>
          {shippedLabel}
        </a>

        <h1
          className="mb-6 animate-fade-in-up text-4xl font-semibold tracking-tight text-canvas-900 sm:text-5xl md:text-6xl dark:text-white"
          style={{ animationDelay: '0.05s', lineHeight: 1.1 }}
        >
          Publishing
          <br className="hidden sm:block" />{' '}
          <span className="text-canvas-500 dark:text-canvas-400">
            on your own terms
          </span>
        </h1>

        <p
          className="mx-auto mb-10 max-w-2xl animate-fade-in-up text-lg leading-relaxed text-canvas-600 sm:text-xl dark:text-canvas-400"
          style={{ animationDelay: '0.1s' }}
        >
          Canvas is a powerful tool for Laravel apps that makes it easy to
          write, edit, and brand your work with a range of publishing tools.
        </p>

        <div
          className="flex animate-fade-in-up flex-row flex-wrap items-center justify-center gap-3"
          style={{ animationDelay: '0.15s' }}
        >
          <a
            href="#install"
            className="inline-flex items-center gap-2 rounded-full border border-transparent bg-canvas-900 px-5 py-2.5 text-sm font-medium text-white transition-all hover:scale-[1.02] hover:bg-canvas-800 active:scale-[0.98] dark:border-canvas-600 dark:bg-canvas-100 dark:text-canvas-900 dark:hover:bg-white"
          >
            Get started
            <ArrowRightIcon className="h-4 w-4" />
          </a>
          <a
            href="https://github.com/austintoddj/canvas"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 rounded-full border border-canvas-200 bg-white px-5 py-2.5 text-sm font-medium text-canvas-700 transition-all hover:scale-[1.02] hover:bg-canvas-50 active:scale-[0.98] dark:border-canvas-700 dark:bg-canvas-900 dark:text-canvas-200 dark:hover:bg-canvas-800"
          >
            <GitHubIcon className="h-4 w-4" />
            View on GitHub
          </a>
        </div>

        <div
          className="mt-16 flex animate-fade-in flex-wrap items-center justify-center gap-x-6 gap-y-3 text-[12px] font-medium text-canvas-500"
          style={{ animationDelay: '0.25s' }}
        >
          <span className="flex items-center gap-1.5">
            <LaravelIcon className="h-3.5 w-3.5" />
            Laravel 13
          </span>
          <span className="flex items-center gap-1.5">
            <PhpIcon className="h-3.5 w-3.5" />
            PHP 8.4
          </span>
          <span className="flex items-center gap-1.5">
            <ReactIcon className="h-3.5 w-3.5" />
            React 19
          </span>
          <span className="flex items-center gap-1.5">
            <TailwindIcon className="h-3.5 w-3.5" />
            Tailwind CSS
          </span>
          <span className="flex items-center gap-1.5">
            <GitHubIcon className="h-3.5 w-3.5" />
            MIT License
          </span>
        </div>
      </div>
    </section>
  )
}
